package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InternAbilityId generated by hbm2java
 */
@Embeddable
public class InternAbilityId implements java.io.Serializable {

	private int internId;
	private int abilityId;
	private String rate;

	public InternAbilityId() {
	}

	public InternAbilityId(int internId, int abilityId, String rate) {
		this.internId = internId;
		this.abilityId = abilityId;
		this.rate = rate;
	}

	@Column(name = "intern_id", nullable = false)
	public int getInternId() {
		return this.internId;
	}

	public void setInternId(int internId) {
		this.internId = internId;
	}

	@Column(name = "ability_id", nullable = false)
	public int getAbilityId() {
		return this.abilityId;
	}

	public void setAbilityId(int abilityId) {
		this.abilityId = abilityId;
	}

	@Column(name = "rate", nullable = false, length = 10)
	public String getRate() {
		return this.rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InternAbilityId))
			return false;
		InternAbilityId castOther = (InternAbilityId) other;

		return (this.getInternId() == castOther.getInternId()) && (this.getAbilityId() == castOther.getAbilityId())
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null && castOther.getRate() != null
						&& this.getRate().equals(castOther.getRate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInternId();
		result = 37 * result + this.getAbilityId();
		result = 37 * result + (getRate() == null ? 0 : this.getRate().hashCode());
		return result;
	}

}
