package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InternAbility generated by hbm2java
 */
@Entity
@Table(name = "intern_ability", catalog = "hus_web")
public class InternAbility implements java.io.Serializable {

	private InternAbilityId id;
	private AbilityDictionary abilityDictionary;
	private InternProfile internProfile;

	public InternAbility() {
	}

	public InternAbility(InternAbilityId id, AbilityDictionary abilityDictionary, InternProfile internProfile) {
		this.id = id;
		this.abilityDictionary = abilityDictionary;
		this.internProfile = internProfile;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "internId", column = @Column(name = "intern_id", nullable = false)),
			@AttributeOverride(name = "abilityId", column = @Column(name = "ability_id", nullable = false)),
			@AttributeOverride(name = "rate", column = @Column(name = "rate", nullable = false, length = 10)) })
	public InternAbilityId getId() {
		return this.id;
	}

	public void setId(InternAbilityId id) {
		this.id = id;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "ability_id", nullable = false, insertable = false, updatable = false)
	public AbilityDictionary getAbilityDictionary() {
		return this.abilityDictionary;
	}

	public void setAbilityDictionary(AbilityDictionary abilityDictionary) {
		this.abilityDictionary = abilityDictionary;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "intern_id", nullable = false, insertable = false, updatable = false)
	public InternProfile getInternProfile() {
		return this.internProfile;
	}

	public void setInternProfile(InternProfile internProfile) {
		this.internProfile = internProfile;
	}

}
