package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrganizationProfile generated by hbm2java
 */
@Entity
@Table(name = "organization_profile", catalog = "hus_web")
public class OrganizationProfile implements java.io.Serializable {

	private Integer id;
	private String name;
	private int employeeCount;
	private int grossRevenue;
	private String address;
	private String contact;
	private String taxNumber;
	private String password;
	private String description;
	private String phone;

	public OrganizationProfile() {
	}

	public OrganizationProfile(String name, int employeeCount, int grossRevenue, String address, String contact,
			String taxNumber, String password) {
		this.name = name;
		this.employeeCount = employeeCount;
		this.grossRevenue = grossRevenue;
		this.address = address;
		this.contact = contact;
		this.taxNumber = taxNumber;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "employee_count", nullable = false)
	public int getEmployeeCount() {
		return this.employeeCount;
	}

	public void setEmployeeCount(int employeeCount) {
		this.employeeCount = employeeCount;
	}

	@Column(name = "gross_revenue", nullable = false)
	public int getGrossRevenue() {
		return this.grossRevenue;
	}

	public void setGrossRevenue(int grossRevenue) {
		this.grossRevenue = grossRevenue;
	}

	@Column(name = "address", nullable = false, length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contact", nullable = false, length = 100)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "tax_number", nullable = false, length = 20)
	public String getTaxNumber() {
		return this.taxNumber;
	}

	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "description", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}


}
