package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Register generated by hbm2java
 */
@Entity
@Table(name = "register", catalog = "hus_web")
public class Register implements java.io.Serializable {

	private Integer id;
	private InternProfile internProfile;
	private Request request;
	private Date dateCreated;
	private Date startDate;
	private Date endDate;

	public Register() {
	}

	public Register(InternProfile internProfile, Request request, Date dateCreated) {
		this.internProfile = internProfile;
		this.request = request;
		this.dateCreated = dateCreated;
	}

	public Register(InternProfile internProfile, Request request, Date dateCreated, Date startDate, Date endDate) {
		this.internProfile = internProfile;
		this.request = request;
		this.dateCreated = dateCreated;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "intern_id", nullable = false)
//	public InternProfile getInternProfile() {
//		return this.internProfile;
//	}
//
//	public void setInternProfile(InternProfile internProfile) {
//		this.internProfile = internProfile;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "request_id", nullable = false)
//	public Request getRequest() {
//		return this.request;
//	}
//
//	public void setRequest(Request request) {
//		this.request = request;
//	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
