package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RequestAbility generated by hbm2java
 */
@Entity
@Table(name = "request_ability", catalog = "hus_web")
public class RequestAbility implements java.io.Serializable {

	private RequestAbilityId id;
	private AbilityDictionary abilityDictionary;
	private Request request;

	public RequestAbility() {
	}

	public RequestAbility(RequestAbilityId id, AbilityDictionary abilityDictionary, Request request) {
		this.id = id;
		this.abilityDictionary = abilityDictionary;
		this.request = request;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "requestId", column = @Column(name = "request_id", nullable = false)),
			@AttributeOverride(name = "abilityId", column = @Column(name = "ability_id", nullable = false)) })
	public RequestAbilityId getId() {
		return this.id;
	}

	public void setId(RequestAbilityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ability_id", nullable = false, insertable = false, updatable = false)
	public AbilityDictionary getAbilityDictionary() {
		return this.abilityDictionary;
	}

	public void setAbilityDictionary(AbilityDictionary abilityDictionary) {
		this.abilityDictionary = abilityDictionary;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "request_id", nullable = false, insertable = false, updatable = false)
	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

}
