package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestAssignment generated by hbm2java
 */
@Entity
@Table(name = "request_assignment", catalog = "hus_web")
public class RequestAssignment implements java.io.Serializable {

	private Integer id;
	private InternProfile internProfile;
	private Request request;
	private Status status;
	private Date startDate;
	private Date endDate;
	private Date dateCreated;

	public RequestAssignment() {
	}

	public RequestAssignment(InternProfile internProfile, Request request) {
		this.internProfile = internProfile;
		this.request = request;
	}

	public RequestAssignment(InternProfile internProfile, Request request, Status status, Date startDate, Date endDate,
			Date dateCreated) {
		this.internProfile = internProfile;
		this.request = request;
		this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
		this.dateCreated = dateCreated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intern_id", nullable = false)
	public InternProfile getInternProfile() {
		return this.internProfile;
	}

	public void setInternProfile(InternProfile internProfile) {
		this.internProfile = internProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "request_id", nullable = false)
	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
