package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Request generated by hbm2java
 */
@Entity
@Table(name = "request", catalog = "hus_web")
public class Request implements java.io.Serializable {

	private long id;
//	private OrganizationProfile organizationProfile;
//	private Status status;
	private String status;
	private String position;
	private int amount;
	private Date dateCreated;
	private String description;
	private String type;
//	private Set requestAbilities = new HashSet(0);
//	private Set registers = new HashSet(0);
//	private Set requestAssignments = new HashSet(0);

	public Request() {
	}

	public Request(String status, String position, int amount,
			Date dateCreated, String type) {
//		this.organizationProfile = organizationProfile;
		this.status = status;
		this.position = position;
		this.amount = amount;
		this.dateCreated = dateCreated;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "organization_id", nullable = false)
//	public OrganizationProfile getOrganizationProfile() {
//		return this.organizationProfile;
//	}
//
//	public void setOrganizationProfile(OrganizationProfile organizationProfile) {
//		this.organizationProfile = organizationProfile;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "status", nullable = false)
//	public Status getStatus() {
//		return this.status;
//	}
//
//	public void setStatus(Status status) {
//		this.status = status;
//	}

	@Column(name = "position", nullable = false, length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "request")
//	public Set getRequestAbilities() {
//		return this.requestAbilities;
//	}
//
//	public void setRequestAbilities(Set requestAbilities) {
//		this.requestAbilities = requestAbilities;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "request")
//	public Set getRegisters() {
//		return this.registers;
//	}
//
//	public void setRegisters(Set registers) {
//		this.registers = registers;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "request")
//	public Set getRequestAssignments() {
//		return this.requestAssignments;
//	}
//
//	public void setRequestAssignments(Set requestAssignments) {
//		this.requestAssignments = requestAssignments;
//	}

}
