package intern.wm.entities;
// Generated Apr 26, 2020 2:36:07 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "hus_web")
public class Status implements java.io.Serializable {

	private Integer id;
	private String name;
//	private Set requests = new HashSet(0);
//	private Set requestAssignments = new HashSet(0);

	public Status() {
	}

	public Status(String name) {
		this.name = name;
	}

	public Status(String name, Set requests, Set requestAssignments) {
		this.name = name;
//		this.requests = requests;
//		this.requestAssignments = requestAssignments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
//	public Set getRequests() {
//		return this.requests;
//	}
//
//	public void setRequests(Set requests) {
//		this.requests = requests;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
//	public Set getRequestAssignments() {
//		return this.requestAssignments;
//	}
//
//	public void setRequestAssignments(Set requestAssignments) {
//		this.requestAssignments = requestAssignments;
//	}

}
